// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';
import {main} from '../models';

export function GetActiveTask():Promise<entity.Task>;

export function GetProjects():Promise<Array<entity.Project>>;

export function GetTasks(arg1:any):Promise<Array<entity.Task>>;

export function IsPausedWorking():Promise<boolean>;

export function IsWorking():Promise<boolean>;

export function PauseWork():Promise<boolean>;

export function ResumeWork():Promise<boolean>;

export function StartTask(arg1:string,arg2:string):Promise<main.StartTaskResponse>;

export function StartWork():Promise<boolean>;

export function StopTask():Promise<boolean>;

export function StopWork():Promise<boolean>;
