// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';

export function GetProjects():Promise<Array<entity.Project>>;

export function GetTasks():Promise<Array<entity.Task>>;

export function Greet(arg1:string):Promise<string>;
