// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveTask() {
  return window['go']['main']['App']['GetActiveTask']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function StartTask(arg1, arg2) {
  return window['go']['main']['App']['StartTask'](arg1, arg2);
}

export function StartWork() {
  return window['go']['main']['App']['StartWork']();
}

export function StopTask() {
  return window['go']['main']['App']['StopTask']();
}

export function StopWork() {
  return window['go']['main']['App']['StopWork']();
}
