// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveTask() {
  return window['go']['main']['App']['GetActiveTask']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetTasks(arg1) {
  return window['go']['main']['App']['GetTasks'](arg1);
}

export function IsPausedWorking() {
  return window['go']['main']['App']['IsPausedWorking']();
}

export function IsWorking() {
  return window['go']['main']['App']['IsWorking']();
}

export function PauseTask() {
  return window['go']['main']['App']['PauseTask']();
}

export function PauseWork() {
  return window['go']['main']['App']['PauseWork']();
}

export function ResumeTask(arg1, arg2) {
  return window['go']['main']['App']['ResumeTask'](arg1, arg2);
}

export function ResumeWork() {
  return window['go']['main']['App']['ResumeWork']();
}

export function StartTask(arg1, arg2) {
  return window['go']['main']['App']['StartTask'](arg1, arg2);
}

export function StartWork() {
  return window['go']['main']['App']['StartWork']();
}

export function StopTask() {
  return window['go']['main']['App']['StopTask']();
}

export function StopWork() {
  return window['go']['main']['App']['StopWork']();
}
